### ISSUE TITLE
venvs no se sube

### ISSUE THREAD

**Issue by eamanu** [michysantillan/agrim#13]
Como este es un grupo bastante avanzado,  me doy el lujo de hacerles este
comentario. Generalmente, la carpeta venv, virtualenvs, etc no se sube. Por
que son binarios, además pesa mucho, y sobre todo contiene, binarios que 
pueden ser facilmente adquiridos/buildeados haciendo un `pip install`  o
con `setuptools`. Por lo que siempre es una buena idea (en Python y cualquier
otro lenguaje) agregar las carpetas de los binarios al `.gitignore`. Este es un archivo
dónde se listan los archivos y carpetas que se quieren ignorar. Y se pueden
utilizar los comodines de Unix. Por lo que podrías agregar en el `.gitignore` 
una lionea que sea `venv/` 

cc: @michysantillan @rmoyano @Eugemo @mnrios1997

**Comment by eamanu** [comment]
Also, las carpetas de configuración de las IDE o editories, tipo `.vscode`,
`.vimrc`, `.idea`, etc, es bueno también no compartirlo (aunque vi varios 
equipos que lo comparten)

**Comment by Eugemo** [comment]
gracias por la aclaracion

**Comment by michysantillan** [comment]
Mi buena recomendación emanuel, no sabia eso, lo voy a hacer. Muchas
gracias

**Comment by rmoyano** [comment]
Gracias Emma, yo revisé que estaban **requirements.txt** y **.gitignore** y fuí directo al directorio a ver el código, lo pasé por alto.

**Comment by eamanu** [comment]
Excelente, no es nada grave, solo si llega a pasar se borra y se hace un nuevo
commit :)

Cierro el issue. Exitos en el curso 2!
