### ISSUE TITLE
Falta README.md

### ISSUE THREAD

**Issue by Eugemo** [michysantillan/agrim#5]
si bien tu proyecto tiene un archivo de requerimientos, lo correcto seria que posea un README.md, donde no solo tengas los requerimientos, sino dependencias, credenciales y todo lo necesario para ejecutarlo correctamente. 
a modo de ejemplo sugiero  esta plantilla [https://gist.github.com/Villanuevand/6386899f70346d4580c723232524d35a](url)
donde podras ver un ejemplo que podras modificar segun tu caso.

**Comment by michysantillan** [comment]
genial Euge, si puedes agregarlo te agradeceria!
